// File generated by Antigravity based on google-services.json and GoogleService-Info.plist
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the flutterfire cli.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the flutterfire cli.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the flutterfire cli.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the flutterfire cli.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCW0Q0RgHZ9XcbPOB0cAPGuSlt34vCpeEY',
    appId: '1:849117174196:android:d995f1baa3a5af282fbae1',
    messagingSenderId: '849117174196',
    projectId: 'dueday-7ab7f',
    storageBucket: 'dueday-7ab7f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPiqzZkvCqFpSwyySu9U0SzYrr3vPD2JE',
    appId: '1:849117174196:ios:66a45f9186f8b9e92fbae1',
    messagingSenderId: '849117174196',
    projectId: 'dueday-7ab7f',
    storageBucket: 'dueday-7ab7f.firebasestorage.app',
    iosClientId:
        '849117174196-tf323dudlkqj4cc9bkkseatf9d72suv4.apps.googleusercontent.com',
    iosBundleId: 'com.dueday.dueDay',
  );
}
